### ISSUE TITLE
Public page link shows 404

### ISSUE THREAD

**Issue by Transisto** [dennisreimann/btcpayserver-plugin-podserver#4]
When clicking 
![image](https://github.com/dennisreimann/btcpayserver-plugin-podserver/assets/388716/eb6d7073-c7b5-4859-9ced-3a0d1fd57609)

It goes to 404 - PAGE NOT FOUND

**Comment by dennisreimann** [comment]
Can you provide more info? 

- Which version of BTCPay Server and PodServer are you using?
- Do you have to Podcast mounted to a domain (Server Settings > Policies)?

**Comment by nostitos** [comment]
No I didn't any app mounted to a domain.

**Comment by Transisto** [comment]
No I didn't had any app mounted to a domain.

**Comment by dennisreimann** [comment]
Can you please upgrade to PodServer v0.3 and see if it also fixes #7.

**Comment by Transisto** [comment]
Yes, all issues fixed
